[package]
name = "img-and-base64"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "img_and_base64"
crate-type = ["cdylib"]

[dependencies]
base64 = "0.21.0"
pyo3 = "0.18.1"
